import numpy as np
from typing import TypeVar, Callable, Any
from numpy.typing import NDArray, ArrayLike
from amisc import System, distribution as distributions
import amisc.distribution
from MCMCIterators.samplers import DelayedRejectionAdaptiveMetropolis
from pem_core import Variable, PathLike, PEM, read_dlm
import math
import random

T = TypeVar("T", bound=np.floating)
F = TypeVar("F", np.floating, float)

def read_output_file(path: PathLike, burn_fraction: float = 0.0):
    """
    Read an output file generated by MCMC.
    TODO: use read_dlm for this.
    """
    dlm = ","
    with open(path, "r") as file:
        header = file.readline().rstrip()

        fields = header.split(dlm)
        var_start = 1
        var_end = len(fields) - 2

        id_ind = 0
        variables = fields[var_start:var_end]
        log_post_ind = len(variables) + 1
        accept_ind = len(variables) + 2

        assert fields[id_ind] == "id"
        assert fields[log_post_ind] == "log_posterior"
        assert fields[accept_ind] == "accepted"

        samples = []
        logposts = []
        accepted = []
        ids = []

        for i, line in enumerate(file):
            fields = line.rstrip().split(dlm)
            accept_str = fields[accept_ind].casefold()

            if accept_str == "true":
                accept = True
            elif accept_str == "false":
                accept = False
            else:
                raise ValueError(f"Invalid accept value {fields[accept_ind]} at row {i} in file {path}.")

            if accept:
                # Create IDs from scratch rather than read ID.
                # This is for compatibility with older runs where a bug led to some duplicate ids.
                id = f"{i:06d}"
                ids.append(id)

            elif len(ids) > 0:
                ids.append(ids[-1])
            else:
                raise ValueError(f"No accepted sample prior to sample {i}")

            logposts.append(float(fields[log_post_ind]))
            samples.append(np.array([float(x) for x in fields[var_start:var_end]]))
            accepted.append(accept)

    # Discard burned samples
    if burn_fraction > 0:
        num_burn = math.floor(burn_fraction * len(samples))
        samples = samples[num_burn:]
        logposts = logposts[num_burn:]
        accepted = accepted[num_burn:]
        ids = ids[num_burn:]

    return variables, np.array(samples), np.array(logposts), np.array(accepted), ids


def _gauss_logpdf_1D(x: F, mean: F, std: F) -> F:
    """
    Gaussian log-likelihood in 1D
    """
    return -0.5 * (np.log(2 * np.pi * std**2) + (x - mean) ** 2 / std**2)

def _relative_l2_norm(data: NDArray[T], observation: NDArray[T]) -> T:
    """
    Compute the L2-normed distance between a data array and observation array,
    relative to the magnitude of the data array.
    """
    num = np.sum((data - observation) ** 2)
    denom = np.sum(data**2)
    return np.sqrt(num / denom)

def _relative_gaussian_likelihood(x: ArrayLike, y: ArrayLike, std: float) -> tuple[float, float]:
    """
    Calculate the gaussian likelihood of the L2 norm of the distance between x and y if the norm is half-normally distributed about zero with standard deviation `std`. 
    Returns the likelihood and the L2 distance
    """
    x_arr = np.asarray(x)
    data_arr = np.asarray(y)
    if x_arr.shape != data_arr.shape:
        raise ValueError(f"Shape of x must match shape of data! Got {x_arr.shape} and {data_arr.shape} instead.")
    
    distance = _relative_l2_norm(x_arr, data_arr)

    # Since the l2-norm is positive-definite, the distribution is a half-normal, so we
    # need to multiply the normal pdf by 2 (or add ln(2) to the log-pdf)
    likelihood = _gauss_logpdf_1D(distance, 0.0, std) + np.log(2)

    return likelihood, distance

def _log_prior(system: System, params: dict[str, ArrayLike]) -> float:
    """
    Compute the log-prior distribution of a system when evaluated at a dictionary of parameter values
    """
    logp = 0.0
    for key, value in params.items():
        var = system.inputs()[key]
        denorm = var.denormalize(value)

        assert var.distribution is not None and isinstance(var.distribution, amisc.distribution.Distribution)
        prior = var.distribution.pdf(np.asarray(denorm))

        if isinstance(prior, np.ndarray):
            prior = prior[0]

        if prior <= 0:
            return -np.inf

        logp += np.log(prior)

    return logp

def _log_posterior(system: System, params: dict[str, ArrayLike], likelihood: Callable[[System, dict[str, ArrayLike]], float]) -> float:

    log_prior = _log_prior(system, params)

    if not np.isfinite(log_prior):
        return -np.inf

    log_likelihood = likelihood(system, params)

    if not np.isfinite(log_likelihood):
        return -np.inf

    return log_prior + log_likelihood


class Sampler:
    variables: list[Variable]
    base_vars: dict[Variable, Any]
    init_sample_file: PathLike | None
    init_cov_file: PathLike | None
    system: PEM

    def __init__(
        self,
        variables,
        data,
        system,
        base_vars,
        opts,
        log_likelihood,
        init_sample_file: PathLike | None = None,
        init_cov_file: PathLike | None = None,
    ):
        self.variables = variables
        self.data = data
        self.system = system
        self.base_vars = base_vars
        self.opts = opts
        self.init_sample_file = init_sample_file
        self.init_cov_file = init_cov_file
        self.logpdf = lambda x: _log_posterior(system, dict(zip(variables, x)), log_likelihood)
        self._init_sample = None
        self._init_cov = None

    def cov(self):
        return self.initial_cov()

    def initial_sample(self):
        if self._init_sample is None:
            # Read initial sample from file or create it from the base variables dict
            if self.init_sample_file is None:
                self._init_sample = np.array([self.base_vars[p] for p in self.variables])
            else:
                index_map = {p.name: i for (i, p) in enumerate(self.variables)}
                self._init_sample = np.zeros(len(self.variables))
                var_dict = read_dlm(self.init_sample_file)
                for k, v in var_dict.items():
                    i = index_map[k]
                    self._init_sample[i] = v[0]

        return self._init_sample

    def initial_cov(self):
        if self._init_cov is None:
            index_map = {p.name: i for (i, p) in enumerate(self.variables)}
            if self.init_cov_file is None:
                variances = np.ones(len(self.variables))

                # Use variable distributions to estimate covariance
                for i, p in enumerate(self.variables):
                    dist = self.system.inputs()[p].distribution
                    if isinstance(dist, distributions.Uniform) or isinstance(dist, distributions.LogUniform):
                        lb, ub = dist.dist_args
                        std: float = (ub - lb) / 4
                    elif isinstance(dist, distributions.Normal):
                        std: float = dist.dist_args[1]
                    elif isinstance(dist, distributions.LogNormal):
                        std: float = dist.base ** dist.dist_args[1]
                    else:
                        raise ValueError(
                            f"Unsupported distribution {dist}. Currently only `Uniform`, `LogUniform`, `Normal` and `LogNormal` are supported."  # noqa: E501
                        )
                    # TODO: fix this typing issue
                    variances[i] = self.system.inputs()[p].normalize(std) ** 2  # type: ignore
                self._init_cov = np.diag(variances)
            else:
                # Construct covariance from file
                # We support the variables being in a different order so we build the covariance up from the index map.
                cov_dict = read_dlm(self.init_cov_file)
                N = len(self.variables)
                self._init_cov = np.zeros((N, N))
                for i, (key1, column) in enumerate(cov_dict.items()):
                    i1 = index_map[key1]
                    for j, (var, key2) in enumerate(zip(column, cov_dict.keys())):
                        i2 = index_map[key2]
                        self._init_cov[i1, i2] = var

            # Verify that the covariance matrix is positive-definite before proceeding.
            # This throws an exception if not.
            np.linalg.cholesky(self._init_cov)
            self.init_cov = np.linalg.cholesky(self._init_cov)
        return self._init_cov


class PriorSampler(Sampler):
    """
    Samples from prior distribution, run model, and evaluates posterior probability
    """

    def __init__(
        self,
        variables,
        data,
        system,
        base_vars,
        opts,
        log_likelihood,
        init_sample_file: PathLike | None = None,
        init_cov_file: PathLike | None = None,
    ):
        super().__init__(variables, data, system, base_vars, opts, log_likelihood, init_sample_file, init_cov_file)

    def __iter__(self):
        return self

    def __next__(self):
        # TODO: fix this typing issue
        sample = np.array([var.normalize(var.distribution.sample((1,)))[0] for var in self.variables]) # type: ignore
        logp = self.logpdf(sample)
        return sample, logp, np.isfinite(logp)


class PreviousRunSampler(Sampler):
    """
    Samples (with replacement) from a previous MCMC run.
    """

    def __init__(
        self,
        variables,
        data,
        system,
        base_vars,
        opts,
        log_likelihood,
        prev_run_file: PathLike,
        init_sample_file: PathLike | None = None,
        init_cov_file: PathLike | None = None,
        burn_fraction: float = 0.5,
    ):
        super().__init__(variables, data, system, base_vars, opts, log_likelihood,init_sample_file, init_cov_file)
        _vars, _samples, _, accepted, _ = read_output_file(prev_run_file)

        # Figure out the first index we should sample.
        self.start_index = math.floor(burn_fraction * len(_samples))

        # associate variable names with columns and remove burned samples
        _samples = np.array(_samples)
        col_dict = {system.inputs()[v]: _samples[self.start_index :, i] for (i, v) in enumerate(_vars)}

        # reorder to match input varible list.
        # this will error if variable lists don't match
        self.samples = np.array([col_dict[v] for v in self.variables]).T
        self.accepted = accepted[self.start_index :]

    def __iter__(self):
        return self

    def sample_index(self):
        return random.randint(0, self.samples.shape[0] - 1)

    def __next__(self):
        # draw until we get an accepted sample
        index = self.sample_index()

        while not self.accepted[index]:
            index = self.sample_index()

        sample = self.samples[index, :]
        logp = self.logpdf(sample)
        return sample, logp, np.isfinite(logp)


class DRAMSampler(Sampler):
    """
    Samples using delayed rejection adaptive metropolis
    """
    def __init__(
        self,
        variables,
        data,
        system,
        base_vars,
        opts,
        log_likelihood,
        init_sample_file: PathLike | None = None,
        init_cov_file: PathLike | None = None,
    ):
        super().__init__(variables, data, system, base_vars, opts, log_likelihood, init_sample_file, init_cov_file)

        self.sampler = DelayedRejectionAdaptiveMetropolis(
            self.logpdf,
            self.initial_sample(),
            self.initial_cov(),
            adapt_start=10,
            eps=1e-6,
            sd=None,
            interval=1,
            level_scale=1e-1,
        )

    # TODO: fix this typing issue
    def cov(self):  # type: ignore
        return self.sampler.cov_chol

    def __iter__(self):
        return iter(self.sampler)